# -*- coding: utf-8 -*-
"""Ride_Hailing_SQL_Queries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jA8REAZ1AP1kp5AkWhvYh0O8Y24j4ZCN
"""

import json
import sqlite3

# ---------------------------------------------------------
# 1. JSON DATA WITH UNIQUE ALPHANUMERIC IDs
# ---------------------------------------------------------

drivers = [
    {"driver_id": "D01AA", "name": "Alex Morgan", "car": "Toyota Prius"},
    {"driver_id": "D02AB", "name": "Priya Shah", "car": "Honda Civic"},
    {"driver_id": "D03AC", "name": "Jordan Kim", "car": "Tesla Model 3"}
]

riders = [
    {"rider_id": "R01BA", "name": "Jamie Lee"},
    {"rider_id": "R02BB", "name": "Carlos Mendez"},
    {"rider_id": "R03BC", "name": "Riley Chen"}
]

trips = [
    {
        "trip_id": "T01CA",
        "driver_id": "D01AA",
        "rider_id": "R01BA",
        "pickup": "Downtown Station",
        "dropoff": "Riverside Market",
        "price": 14.75
    },
    {
        "trip_id": "T02CB",
        "driver_id": "D02AB",
        "rider_id": "R02BB",
        "pickup": "Airport Terminal B",
        "dropoff": "Grand Hotel Lobby",
        "price": 32.10
    },
    {
        "trip_id": "T03CC",
        "driver_id": "D03AC",
        "rider_id": "R03BC",
        "pickup": "Central Library",
        "dropoff": "Eastwood Apartments",
        "price": 9.50
    }
]

print("JSON data created with unique alphanumeric IDs.")


# ---------------------------------------------------------
# 2. CREATE SQLITE DATABASE
# ---------------------------------------------------------

conn = sqlite3.connect("rides.db")
cur = conn.cursor()

cur.execute("DROP TABLE IF EXISTS Driver")
cur.execute("DROP TABLE IF EXISTS Rider")
cur.execute("DROP TABLE IF EXISTS Trip")

cur.execute("""
CREATE TABLE Driver (
    driver_id TEXT PRIMARY KEY,
    name TEXT,
    car TEXT
)
""")

cur.execute("""
CREATE TABLE Rider (
    rider_id TEXT PRIMARY KEY,
    name TEXT
)
""")

cur.execute("""
CREATE TABLE Trip (
    trip_id TEXT PRIMARY KEY,
    driver_id TEXT,
    rider_id TEXT,
    pickup TEXT,
    dropoff TEXT,
    price REAL,
    FOREIGN KEY(driver_id) REFERENCES Driver(driver_id),
    FOREIGN KEY(rider_id) REFERENCES Rider(rider_id)
)
""")

conn.commit()
print("Database and tables created.")

# ---------------------------------------------------------
# 3. INSERT JSON RECORDS INTO TABLES
# ---------------------------------------------------------

for d in drivers:
    cur.execute("INSERT INTO Driver VALUES (?, ?, ?)",
                (d["driver_id"], d["name"], d["car"]))

for r in riders:
    cur.execute("INSERT INTO Rider VALUES (?, ?)",
                (r["rider_id"], r["name"]))

for t in trips:
    cur.execute("INSERT INTO Trip VALUES (?, ?, ?, ?, ?, ?)",
                (t["trip_id"], t["driver_id"], t["rider_id"],
                 t["pickup"], t["dropoff"], t["price"]))

conn.commit()
print("JSON records inserted into database.")

# ---------------------------------------------------------
# 4. QUERY THE TRIP TABLE IN VARIOUS WAYS
# ---------------------------------------------------------

print("\n--- All Trips ---")
for row in cur.execute("SELECT * FROM Trip"):
    print(row)

print("\n# Query: All Trips")
cur.execute("SELECT * FROM Trip")
rows = cur.fetchall()
for row in rows:
    print(row)

print("\n--- Trips with Driver and Rider Names (JOIN) ---")
query = """
SELECT Trip.trip_id, Driver.name AS driver,
    Rider.name AS rider,
    Trip.pickup,
    Trip.dropoff,
    Trip.price
FROM Trip
JOIN Driver ON Trip.driver_id = Driver.driver_id
JOIN Rider ON Trip.rider_id = Rider.rider_id
"""
for row in cur.execute(query):
    print(row)

query = """
SELECT Trip.trip_id,
       Driver.name AS driver,
       Rider.name AS rider,
       Trip.pickup,
       Trip.dropoff,
       Trip.price
FROM Trip
JOIN Driver ON Trip.driver_id = Driver.driver_id
JOIN Rider  ON Trip.rider_id = Rider.rider_id
"""
cur.execute(query)
rows = cur.fetchall()
for row in rows:
    print(row)

print("\n--- Trips costing more than $15 ---")
for row in cur.execute("SELECT * FROM Trip WHERE price > 15"):
    print(row)



print("\n# Query: Trips costing more than $20")
cur.execute("""
SELECT trip_id, price, pickup, dropoff
FROM Trip
WHERE price > 20
""")
rows = cur.fetchall()
for row in rows:
    print(row)

print("\n--- Count of Trips per Driver ---")
query = """
SELECT Driver.name, COUNT(Trip.trip_id) AS num_trips
FROM Driver
LEFT JOIN Trip ON Driver.driver_id = Trip.driver_id
GROUP BY Driver.driver_id
"""
for row in cur.execute(query):
    print(row)

print("\n# Query: Average Trip Price per Driver")
query = """
SELECT Driver.name,
       AVG(Trip.price) AS avg_price
FROM Driver
LEFT JOIN Trip ON Driver.driver_id = Trip.driver_id
GROUP BY Driver.driver_id
"""
cur.execute(query)
rows = cur.fetchall()
for row in rows:
    print(row)

print("\n# Query: Number of Trips per Rider")
query = """
SELECT Rider.name,
       COUNT(Trip.trip_id) AS num_trips
FROM Rider
LEFT JOIN Trip ON Rider.rider_id = Trip.rider_id
GROUP BY Rider.rider_id
"""
cur.execute(query)
rows = cur.fetchall()
for row in rows:
    print(row)



print("\n# Query: Trips Ordered by Price (Descending)")
cur.execute("""
SELECT trip_id, price, pickup, dropoff
FROM Trip
ORDER BY price DESC
""")
rows = cur.fetchall()
for row in rows:
    print(row)

print("\n# Query: Trips for Driver D01AA")
cur.execute("""
SELECT trip_id, pickup, dropoff, price
FROM Trip
WHERE driver_id = 'D01AA'
""")
rows = cur.fetchall()
for row in rows:
    print(row)

print("\n--- Average Trip Price ---")
for row in cur.execute("SELECT AVG(price) FROM Trip"):
    print("Average price:", row[0])









conn.close()
print("\nAll done.")